# https://github.com/markitosgv/JWTRefreshTokenBundle

gesdinet_jwt_refresh_token:
  ttl: 2592000
  ttl_update: true
  firewall: api
  token_parameter_name: refresh_token
  return_expiration: true
  return_expiration_parameter_name: refresh_token_expiration
