services:

  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - ENABLE_XDEBUG=${ENABLE_XDEBUG}
    environment:
      - PHP_IDE_CONFIG="serverName=Docker"
      - DATABASE_URL=postgresql://symfony:symfony@database/symfony?serverVersion=17&charset=utf8
    volumes:
      - ./../:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  database:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
